name: deploy
on:
  push:
    branches:
      - v5

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
      - name: Deploy
        run: $(npm bin)/firebase deploy --project reactrouter-com --non-interactive --force --message "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" --token ${{ secrets.FIREBASE_TOKEN }}
